// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhpavkfidxueqlzzghxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJocGF2a2ZpZHh1ZXFsenpnaHhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzk3MjQsImV4cCI6MjA3MTg1NTcyNH0.rS8MhFR1sDEW6KdWe1s7_H-dCNMpuTgrJ_p9Ykhj_Hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});